# This action run tests and builds a flutter application. 
# Also sends notification to a Telegram chat

name: Flutter mobile CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.3.0
      with:
          channel: 'stable'
    - name: Send PR notification to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          *${{ github.actor }}* PR-${{ github.event.number }} en *${{ github.event.repository.name }}*
          
          Se ha creado un nuevo PR.
          Pueden revisarlo en [Url del repositorio]${{ github.event.number }}
          Realizando build...
    - name: Build
      run: |
        cd e_commerce
        flutter pub get
        flutter test
        flutter build apk --split-per-abi
    - name: Send artifacts to Telegram
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          *${{ github.actor }}* PR-${{ github.event.number }} en *${{ github.event.repository.name }}*
          
          Build terminado con éxito.
        document: build/app/outputs/apk/release/app-arm64-v8a-release.apk
    - name: Send error to Telegram
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          ${{ github.actor }} PR-${{ github.event.number }} en *${{ github.event.repository.name }}*
          
          Ha ocurrido un error durante el build
    - uses: actions/upload-artifact@v1
      with:
        name: APKs
        path: build/app/outputs/apk/release