name: Build and deploy web 

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.3.0
      with:
          channel: 'beta'
    - name: Send PR notification to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          *${{ github.actor }}* PR-${{ github.event.number }} en *${{ github.event.repository.name }}*
          
          Se ha creado un nuevo PR.
          Pueden revisarlo en [Github Url]${{ github.event.number }}
          Realizando build...
    - name: Replace version
      run: sed -i -e 's/version=[0-9]\+/version=${{ github.run_number }}/g' web/index.html
    - name: Build
      run: |
        flutter config --enable-web
        flutter pub get
        flutter build web
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Send artifacts to Telegram
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          *${{ github.actor }}* PR-${{ github.event.number }} en *${{ github.event.repository.name }}*
          
          Build terminado con éxito. Puedes ver la página aquí: [Web-URL]
    - name: Send error to Telegram
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          ${{ github.actor }} PR-${{ github.event.number }} en *${{ github.event.repository.name }}*
          
          Ha ocurrido un error durante el build    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Web artifacts
        path: build/web
    

