name: Deploy CMS to production

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  deploy_cms_to_prod:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 19
    - name: Getting dependencies
      run: npm --prefix ./cms install ./cms
    - name: Build
      run: yarn --cwd ./cms/ run build
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DER_TACNA }}'
        projectId: <project-id>
        channelId: live
